### ISSUE TITLE
PVC size and speed

### ISSUE THREAD

**Issue by Davincible** [UpCloudLtd/upcloud-csi#31]
Just stumbled upon this project, and I am really excited to see this develop. Really looking forward to v1.0. This project greatly helps the k8s experience on UpCloud.

After some testing, I stumbled upon two things;

1. Min size of 10Gb, as some volumes don't require much, would it be possible to create smaller volumes?
2. Performance seems to be rather slow (especially for IOPS):
   ```
   Raw performance: 75 Mb/s RW
   Maystor: 50 Mb/s RW
   TopoLVM: 25 Mb/s RW
   UpCloud CSI: 3740 Kb/s RW
   ``` 
   Most notable to me was that the RW speed tends to baseline around a few Kb, but sporadically shoots up to 25Mb/s - 80Mb/s

Benchmark:
```bash
kubectl exec -n fio-testing -it fio -- fio --name=benchtest --size=800m --filename=/volume/test --direct=1 --rw=randrw --bs=4k --iodepth=16 --numjobs=8 --time_based --runtime=60
```

**Comment by peknur** [comment]
Hi @Davincible !

Thank you for your feedback! 

1. Currently 10Gb storage is smallest unit that we can provision from our [storage service](https://developers.upcloud.com/1.3/9-storages/).  
2. I run your test yesterday and got 73MiB/s RW speed. Maybe there was some other disturbance (e.g. host load, network ..) when you ran that test. Performance should be close to what performance is when the storage is attached and used directly.

**Comment by Davincible** [comment]
Are there plans to change this? Or how would you recommend going about creating smaller volumes, since I think you can only have one default storageclass in k8s.

After some more testing, I found out that (at least partly) it's related to my setup. I run Talos Linux with Cilium CNI, and if I don't install Cilium on cluster creation it appears to work. But have to do some more testing to confirm

**Comment by vtorhonen** [comment]
> Are there plans to change this?

We are looking into this! Another limiting factor from our side is that you can only attach 8 volumes per server.

> Or how would you recommend going about creating smaller volumes, since I think you can only have one default storageclass in k8s.

Since it's a limitation on our storage service, you won't be able to go around it in the driver. Currently only workaround is to set the PVC storage request size to 10 GB, which you can do on a per volume basis of course.

**Comment by Davincible** [comment]
I see, after thinking more about the problem I thought it could be nice to have something like TopoLvm but extend it to add extra disks when space runs out. So instead of directly mounting the entire disk you add an abstraction layer on top

**Comment by Davincible** [comment]
Turns out some UpCloud data centers are underperforming, not an issue of this CSI.

See https://github.com/Davincible/UpCloud-Bencher for details.

I'll keep the issue open to track progress on the number of drives mountable, and minimum drive size.

**Comment by thevilledev** [comment]
Hey @Davincible!

We have recently lowered our storage backend limits and it is now possible to create as small as 1 GB storage devices. Naturally these can also be created through our CSI driver. This should help with cases where you've for example tried to install a Helm chart, which has used a default storage request size that has been lower than what our API has allowed to use (less than 10 GB previously). Now you can install them without any hassle.

And thank you for the detailed benchmarking details! As for individual storage performance issues within our datacenters I would advise you to reach out to our support. Thanks!

Closing off the issue as there's no CSI driver specific left to be done here.
