### ISSUE TITLE
Expansion support?

### ISSUE THREAD

**Issue by llarsson** [UpCloudLtd/upcloud-csi#7]
Please clarify regarding support for [expansion of Persistent Volumes](https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/) for this CSI driver.

**Comment by vtorhonen** [comment]
Hey @llarsson! We've just pushed volume expansion support to `alpha` branch. Just pull the latest from `ghcr.io/upcloudltd/upcloud-csi:alpha` and you're good to go. :+1:
